// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDTIavHaDHe4s-3lqNju23z1lBlONpxhM',
    appId: '1:922842256919:web:18f4e2cc12f18d2f0e6e52',
    messagingSenderId: '922842256919',
    projectId: 'wheelsmasail-f77f3',
    authDomain: 'wheelsmasail-f77f3.firebaseapp.com',
    storageBucket: 'wheelsmasail-f77f3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcXccP_ve3DAJdoYgKrhOMQ6QB-5zG2I4',
    appId: '1:922842256919:android:16242cca5bb3a9b10e6e52',
    messagingSenderId: '922842256919',
    projectId: 'wheelsmasail-f77f3',
    storageBucket: 'wheelsmasail-f77f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmRBh1dvPImGFaXwuXcVqbt9f4oHwsZ9c',
    appId: '1:922842256919:ios:0f0f628deb64e6a20e6e52',
    messagingSenderId: '922842256919',
    projectId: 'wheelsmasail-f77f3',
    storageBucket: 'wheelsmasail-f77f3.appspot.com',
    iosClientId: '922842256919-kksssofib17lmjc6jkpfpl7keiblve28.apps.googleusercontent.com',
    iosBundleId: 'com.example.wheelsmasail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmRBh1dvPImGFaXwuXcVqbt9f4oHwsZ9c',
    appId: '1:922842256919:ios:0f0f628deb64e6a20e6e52',
    messagingSenderId: '922842256919',
    projectId: 'wheelsmasail-f77f3',
    storageBucket: 'wheelsmasail-f77f3.appspot.com',
    iosClientId: '922842256919-kksssofib17lmjc6jkpfpl7keiblve28.apps.googleusercontent.com',
    iosBundleId: 'com.example.wheelsmasail',
  );

}